name: CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - name: Get runner environment variables
      id: runner
      uses: TheTechsTech/action-environment-info@v1.0.3
    - name: Print output
      id: output
      run: |
        echo ${{ format('platform: {0}, arch: {1}, release: {2}, version: {3}, hostname: {4}, name: {5}', steps.runner.outputs.platform, steps.runner.outputs.arch, steps.runner.outputs.release, steps.runner.outputs.version, steps.runner.outputs.hostname, steps.runner.outputs.name) }}
