name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-2019, ubuntu-18.04]
    steps:
    - name: Get runner environment variables
      id: runner
      uses: techno-express/action-environment-info@v1.1
    - name: Print output
      id: output
      run: |
        echo ${{ format('platform: {0}, arch: {1}, release: {2}', steps.runner.outputs.platform, steps.runner.outputs.arch, steps.runner.outputs.release) }}
